export const BUSINESS = [
  {
    phase: 1,
    title: 'Legal & structure',
    items: [
      'Register business name with CAC (Peregrine Solutions)',
      'Open a dedicated business bank account',
      'Brief a Nigerian tech lawyer for contracts & compliance',
      'Get NDAs signed by all founding team members',
      'Draft independent contractor agreement for chefs',
      'Register trademark for HomeOS.ng and ChefGo',
      'Review NDPR data compliance requirements',
    ],
  },
  {
    phase: 1,
    title: 'Finance & admin',
    items: [
      'Set up Paystack or Flutterwave merchant account',
      'Create a basic financial model / budget for Year 1',
    ],
  },
  {
    phase: 1,
    title: 'Chef supply — pre-launch',
    items: [
      'Build list of 50+ target chefs in Ikeja (Instagram, WhatsApp)',
      'Create chef onboarding pitch one-pager',
      'Begin direct outreach — target 30 chefs in active conversations',
      'Do a live test run with at least 3 real chefs — walk them through the onboarding yourself and note every point of confusion',
      'Set chef pricing expectations and explain commission structure',
      'Collect chef IDs and kitchen photos for verification',
      'Get 5 chefs fully verified and live before any customer sees the platform',
    ],
  },
  {
    phase: 1,
    title: 'Brand & social media',
    items: [
      'Finalise brand kit (logo, green palette, typography)',
      'Set up and optimise all social media profiles',
      'Post at least once on X and Instagram this week — even just introducing the product',
      'DM 10 food vendors on Instagram this week about joining as founding chefs',
    ],
  },
  {
    phase: 2,
    title: 'Marketing & growth',
    items: [
      'Reach out to estate management in Ikeja — GRA, Omole, Magodo',
      'Approach 3–5 companies in Ikeja about home chef benefits for their staff',
      'Draft a short pitch for Techpoint or a Nigerian startup blog — one paragraph, what HomeOS does, why it matters, where to sign up',
      'DM food vendors and home cooks in Ikeja on Instagram — not as influencers, just as potential founding chefs',
    ],
  },
  {
    phase: 2,
    title: 'Ikeja Launch',
    items: [
      'Run Instagram and TikTok ads targeting Ikeja — professionals, dual-income households, ages 25–40',
      'Get 50 real people in Ikeja to sign up before launch day — DMs, word of mouth, WhatsApp groups, whatever works',
      'Identify 3–5 active estate or residential WhatsApp groups in Ikeja and get the platform in front of them',
      'Have at least 5 verified chefs based in or close to Ikeja before announcing the launch',
      'Pick a launch date and work backwards — what needs to be done the week before, 3 days before, day of',
      'Collect and publish first 10 real customer testimonials',
      'Coordinate launch day — social push + estate activation',
    ],
  },
  {
    phase: 2,
    title: 'Operations',
    items: [
      'Hire operations/admin team member',
      'After the test runs, write down what a good chef session actually looks like — use that as the bar going forward',
      'Decide now: when a customer complains, who picks it up and how fast — write it in one paragraph',
      'Set a simple rule — every complaint gets a response within 3 hours during working hours',
      'Write down exactly how you onboarded the first chef, step by step — that becomes the process',
      'Check in with active chefs once a month — how are bookings going, any issues, what do they need',
      'Sit in on or follow up after the first 10 sessions personally — don\'t wait for the data to tell you what went wrong',
    ],
  },
]

export const DEV = [
  {
    phase: 1,
    title: 'Core infrastructure',
    items: [
      'Finalise database schema (users, chefs, bookings, wallets, reviews)',
      'Set up cloud hosting environment (AWS / DigitalOcean)',
      'Configure CI/CD pipeline for staging and production',
      'Implement JWT authentication and session management',
      'Set up SSL, HTTPS, and security headers',
      'Configure PostgreSQL with Redis caching layer',
      'Set up error logging and monitoring (Sentry)',
    ],
  },
  {
    phase: 1,
    title: 'Auth & verification',
    items: [
      'Email OTP signup via Termii (SMS + WhatsApp fallback)',
      'Customer ID verification flow (upload + admin review)',
      'Chef ID and kitchen photo upload + verification workflow',
      'Admin dashboard — verification queue and approve/reject flow',
      'Verified badge display on chef and customer profiles',
    ],
  },
  {
    phase: 1,
    title: 'Browse & discovery',
    items: [
      'Homepage — browse chefs without login (browse-first UX)',
      'Chef profile pages (bio, photos, menu, ratings, reviews)',
      'Location-based chef search and sorting',
      'Filter by service type, cuisine, price range, availability',
      'Google Maps integration for distance and address autocomplete',
    ],
  },
  {
    phase: 1,
    title: 'Booking flow',
    items: [
      'One-off booking creation (date, time, service type, preferences)',
      'Recurring booking setup with schedule automation (BullMQ)',
      'Ingredient selection — customer provides vs chef provides',
      'Booking confirmation emails and push notifications (Firebase FCM)',
      'Chef booking accept / decline flow with timeout logic',
      'Cancellation and rescheduling with policy enforcement',
    ],
  },
  {
    phase: 1,
    title: 'Payments & wallet',
    items: [
      'Paystack / Flutterwave wallet top-up (card + bank transfer + USSD)',
      'Service fee calculation — 10% added to chef rate at checkout',
      'Ingredient markup logic (15% when chef provides)',
      'Escrow hold during active session',
      'Automated funds release to chef on session completion',
      'Refund logic (no-show full refund, cancellation partial)',
      'Wallet transaction history screen',
      '2% Dispute Reserve auto-deduction per transaction',
    ],
  },
  {
    phase: 1,
    title: 'Session & safety',
    items: [
      'Mutual check-in / check-out with timestamp logging',
      'Unresolved check-in auto-flag after 30 minutes',
      'In-app emergency button — admin escalation trigger',
      'Share session feature (send details to trusted contact)',
      'In-app chat between chef and customer (Socket.io)',
      'Real-time booking status updates via WebSocket',
    ],
  },
  {
    phase: 1,
    title: 'Reviews & ratings',
    items: [
      'Post-session review prompt (customer rates chef)',
      'Private chef-side customer rating system',
      'Star rating display on chef profiles with rolling average',
      'Review text display with date and session type',
      'Review flagging and admin moderation workflow',
    ],
  },
  {
    phase: 1,
    title: 'Admin dashboard',
    items: [
      'Chef verification queue (ID review, approve/reject)',
      'Live bookings overview and status tracking',
      'Dispute management panel (evidence, resolution, refund)',
      'Wallet and transaction monitoring',
      'Chef performance metrics and flag tracking',
      'User management (suspend, verify, reset)',
      'Platform analytics (orders, revenue, zone activity)',
    ],
  },
  {
    phase: 2,
    title: 'Loyalty & subscriptions',
    items: [
      'Loyalty tier engine — Guest, Resident, Household, Estate',
      'Tier progress tracker on customer profile',
      'Subscription management — Plus (₦6k/mo) and Premium (₦15k/mo)',
      'Subscription discount logic applied at checkout',
      'Subscription-gated features (priority queue, enhanced dispute cover)',
      'Recurring meal plan discount stacking logic',
      'Subscription billing automation and renewal reminders',
    ],
  },
  {
    phase: 2,
    title: 'Chef analytics dashboard',
    items: [
      'Earnings dashboard — weekly, monthly, cumulative',
      'Booking trends by day, time, and neighbourhood',
      'Review sentiment summary (AI-powered themes)',
      'Customer retention rate per chef',
      'Performance vs zone average benchmarking',
      'Income forecast based on confirmed upcoming bookings',
    ],
  },
  {
    phase: 2,
    title: 'Performance & mobile',
    items: [
      '3G performance audit — all pages under 3s load time',
      'Offline-first screens for booking details and check-in/out',
      'Action queue for offline actions (sync on reconnect)',
      'iOS build via Capacitor — App Store submission',
      'Android build via Capacitor — Play Store submission',
      'Load testing — 2,000 concurrent users',
      'Security audit — penetration testing, OWASP checklist',
    ],
  },
]
