export const BUSINESS = [
  {
    phase: 1,
    title: 'Legal & structure',
    items: [
      'Register business name with CAC (Peregrine Solutions)',
      'Open a dedicated business bank account',
      'Brief a Nigerian tech lawyer for contracts & compliance',
      'Get NDAs signed by all founding team members',
      'Draft independent contractor agreement for chefs',
      'Register trademark for HomeOS.ng and ChefGo',
      'Review NDPR data compliance requirements',
    ],
  },
  {
    phase: 1,
    title: 'Finance & admin',
    items: [
      'Set up bookkeeping (Wave / QuickBooks / accountant)',
      'Set up company email system (Google Workspace)',
      'Set up Paystack / Flutterwave merchant account',
      'Create a basic financial model / budget for Year 1',
      'Draft investor brief distribution list',
    ],
  },
  {
    phase: 1,
    title: 'Chef supply — pre-launch',
    items: [
      'Build list of 50+ target chefs in Lekki/VI (Instagram, WhatsApp)',
      'Create chef onboarding pitch one-pager',
      'Begin direct outreach — target 30 chefs in active conversations',
      'Conduct meetings / calls with interested chefs',
      'Set chef pricing expectations and explain commission structure',
      'Collect chef IDs and kitchen photos for verification',
      'Shortlist 30 verified founding chefs ready for launch',
    ],
  },
  {
    phase: 1,
    title: 'Brand & social media',
    items: [
      'Finalise brand kit (logo, green palette, typography)',
      'Secure @homeos.ng on Instagram, X, TikTok, LinkedIn',
      'Set up and optimise all social media profiles',
      'Create a content calendar for 30 days before launch',
      'Design first 9 Instagram grid posts (chef spotlights, teasers)',
      'Gather photography of real chefs and food',
      'Produce teaser video for Instagram / TikTok',
    ],
  },
  {
    phase: 2,
    title: 'Marketing & growth',
    items: [
      'Identify 20–30 nano-influencers in Lagos food / lifestyle space',
      'Identify 5–10 micro-influencers for paid partnerships',
      'Reach out to estate management in Lekki Phase 1, Oniru, Chevron/VGC',
      'Negotiate estate partnership agreements',
      'Contact admins of Lagos estate and professional WhatsApp groups',
      'Design estate activation flyers and QR codes',
      'Approach 3–5 Lagos companies for corporate wellness partnerships',
      'Draft PR pitch for Techpoint, Nairametrics, Business Day',
    ],
  },
  {
    phase: 2,
    title: 'Waitlist & launch',
    items: [
      'Build and publish waitlist landing page with referral incentive',
      'Set up automated waitlist confirmation email',
      'Run targeted Instagram and TikTok ads to Lekki/VI demographic',
      'Track waitlist signups by zone — target 500 before launch',
      'Invite first 50 founding customers for beta access',
      'Collect and publish first 10 real customer testimonials',
      'Coordinate launch day — social push + estate activation',
    ],
  },
  {
    phase: 2,
    title: 'Operations',
    items: [
      'Hire operations/admin team member',
      'Define chef quality standards and review rubric',
      'Build customer support workflow and escalation process',
      'Set admin response SLAs (disputes, verifications, complaints)',
      'Document chef onboarding standard operating procedure',
      'Create weekly chef check-in routine',
      'Monitor first 100 sessions manually for quality insights',
    ],
  },
]

export const DEV = [
  {
    phase: 1,
    title: 'Core infrastructure',
    items: [
      'Finalise database schema (users, chefs, bookings, wallets, reviews)',
      'Set up cloud hosting environment (AWS / DigitalOcean)',
      'Configure CI/CD pipeline for staging and production',
      'Implement JWT authentication and session management',
      'Set up SSL, HTTPS, and security headers',
      'Configure PostgreSQL with Redis caching layer',
      'Set up error logging and monitoring (Sentry)',
    ],
  },
  {
    phase: 1,
    title: 'Auth & verification',
    items: [
      'Email OTP signup via Termii (SMS + WhatsApp fallback)',
      'Customer ID verification flow (upload + admin review)',
      'Chef ID and kitchen photo upload + verification workflow',
      'Admin dashboard — verification queue and approve/reject flow',
      'Verified badge display on chef and customer profiles',
    ],
  },
  {
    phase: 1,
    title: 'Browse & discovery',
    items: [
      'Homepage — browse chefs without login (browse-first UX)',
      'Chef profile pages (bio, photos, menu, ratings, reviews)',
      'Location-based chef search and sorting',
      'Filter by service type, cuisine, price range, availability',
      'Google Maps integration for distance and address autocomplete',
    ],
  },
  {
    phase: 1,
    title: 'Booking flow',
    items: [
      'One-off booking creation (date, time, service type, preferences)',
      'Recurring booking setup with schedule automation (BullMQ)',
      'Ingredient selection — customer provides vs chef provides',
      'Booking confirmation emails and push notifications (Firebase FCM)',
      'Chef booking accept / decline flow with timeout logic',
      'Cancellation and rescheduling with policy enforcement',
    ],
  },
  {
    phase: 1,
    title: 'Payments & wallet',
    items: [
      'Paystack / Flutterwave wallet top-up (card + bank transfer + USSD)',
      'Service fee calculation — 10% added to chef rate at checkout',
      'Ingredient markup logic (15% when chef provides)',
      'Escrow hold during active session',
      'Automated funds release to chef on session completion',
      'Refund logic (no-show full refund, cancellation partial)',
      'Wallet transaction history screen',
      '2% Dispute Reserve auto-deduction per transaction',
    ],
  },
  {
    phase: 1,
    title: 'Session & safety',
    items: [
      'Mutual check-in / check-out with timestamp logging',
      'Unresolved check-in auto-flag after 30 minutes',
      'In-app emergency button — admin escalation trigger',
      'Share session feature (send details to trusted contact)',
      'In-app chat between chef and customer (Socket.io)',
      'Real-time booking status updates via WebSocket',
    ],
  },
  {
    phase: 1,
    title: 'Reviews & ratings',
    items: [
      'Post-session review prompt (customer rates chef)',
      'Private chef-side customer rating system',
      'Star rating display on chef profiles with rolling average',
      'Review text display with date and session type',
      'Review flagging and admin moderation workflow',
    ],
  },
  {
    phase: 1,
    title: 'Admin dashboard',
    items: [
      'Chef verification queue (ID review, approve/reject)',
      'Live bookings overview and status tracking',
      'Dispute management panel (evidence, resolution, refund)',
      'Wallet and transaction monitoring',
      'Chef performance metrics and flag tracking',
      'User management (suspend, verify, reset)',
      'Platform analytics (orders, revenue, zone activity)',
    ],
  },
  {
    phase: 2,
    title: 'Loyalty & subscriptions',
    items: [
      'Loyalty tier engine — Guest, Resident, Household, Estate',
      'Tier progress tracker on customer profile',
      'Subscription management — Plus (₦6k/mo) and Premium (₦15k/mo)',
      'Subscription discount logic applied at checkout',
      'Subscription-gated features (priority queue, enhanced dispute cover)',
      'Recurring meal plan discount stacking logic',
      'Subscription billing automation and renewal reminders',
    ],
  },
  {
    phase: 2,
    title: 'Chef analytics dashboard',
    items: [
      'Earnings dashboard — weekly, monthly, cumulative',
      'Booking trends by day, time, and neighbourhood',
      'Review sentiment summary (AI-powered themes)',
      'Customer retention rate per chef',
      'Performance vs zone average benchmarking',
      'Income forecast based on confirmed upcoming bookings',
    ],
  },
  {
    phase: 2,
    title: 'Performance & mobile',
    items: [
      '3G performance audit — all pages under 3s load time',
      'Offline-first screens for booking details and check-in/out',
      'Action queue for offline actions (sync on reconnect)',
      'iOS build via Capacitor — App Store submission',
      'Android build via Capacitor — Play Store submission',
      'Load testing — 2,000 concurrent users',
      'Security audit — penetration testing, OWASP checklist',
    ],
  },
]
